title: GamerCoder
description: >
  GamerCoder is a fullstack developer from the United States. He is currently the owner of Team Inceptus.

baseurl: ""
url: "https://gamercoder.teaminceptus.us"
github_username: GamerCoder

markdown: kramdown